const UUID_REGEX =
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

export function isUuid(value?: string | null): value is string {
  return Boolean(value) && UUID_REGEX.test(value as string);
}

/**
 * Creates a resolver for client-only row ids generated by editors such as
 * StyleOperationStepTable (e.g. "new-<ts>", "child-<ts>-<rand>",
 * "group-<ts>") before they've ever been saved. Some backend endpoints
 * (e.g. PO-product operation steps) insert an incoming `id` verbatim into a
 * `uuid` column instead of validating/remapping it server-side like their
 * Style-scoped counterpart does — sending a non-UUID string there fails
 * with either a Postgres "invalid input syntax for type uuid" error or a
 * class-validator "must be a UUID" 400, depending on the DTO.
 *
 * `resolveId` returns an already-valid UUID unchanged, and maps any other
 * value to a freshly generated real UUID. The mapping is memoized per
 * resolver instance, so a parent row's `id` and a child row's
 * `parentStepId` — which start out as the exact same temp string — resolve
 * to the same real UUID, preserving the parent/child link after save.
 */
export function createTempIdResolver() {
  const tempIdToRealId = new Map<string, string>();
  return function resolveId(id?: string | null): string | undefined {
    if (!id) return undefined;
    if (isUuid(id)) return id;
    if (!tempIdToRealId.has(id)) tempIdToRealId.set(id, crypto.randomUUID());
    return tempIdToRealId.get(id);
  };
}
