import { useState } from "react";
import { useForm } from "react-hook-form";
import axios from "axios";
import { Alert, Button, Input, Select } from "@/components/shared";
import { addBomLineFormSchema, type AddBomLineFormValues } from "../schemas/bom.schema";
import { useAddBomLine, useBomMaterialOptions } from "../hooks/useBomLines";
import { useDebouncedValue } from "../hooks/useDebouncedValue";

function message(error: unknown, fallback: string): string {
  return axios.isAxiosError(error) && typeof error.response?.data?.message === "string"
    ? error.response.data.message
    : fallback;
}

export function BomMaterialSelector({ bomId }: { bomId: string }) {
  const [search, setSearch] = useState("");
  const debouncedSearch = useDebouncedValue(search.trim());
  const materials = useBomMaterialOptions(debouncedSearch);
  const addLine = useAddBomLine(bomId);
  const { register, handleSubmit, reset, setError, formState } = useForm<AddBomLineFormValues>({
    defaultValues: {
      materialId: "",
      consumptionPerUnit: 1,
      unitCost: undefined,
      orderIndex: 0,
    },
  });

  const submit = async (values: AddBomLineFormValues) => {
    const result = addBomLineFormSchema.safeParse(values);
    if (!result.success) {
      result.error.issues.forEach((issue) =>
        setError(issue.path[0] as keyof AddBomLineFormValues, { message: issue.message }),
      );
      return;
    }
    try {
      await addLine.mutateAsync(result.data);
      reset({ materialId: "", consumptionPerUnit: 1, unitCost: undefined, orderIndex: 0 });
    } catch {
      /* The API error is rendered below. */
    }
  };

  return (
    <section aria-labelledby="add-bom-line-title" className="space-y-4">
      <div>
        <h2
          id="add-bom-line-title"
          className="text-theme-lg font-semibold text-gray-900 dark:text-white"
        >
          Add material line
        </h2>
        <p className="text-theme-sm mt-1 text-gray-500 dark:text-gray-400">
          Only Active materials are returned. Snapshots are generated by the server.
        </p>
      </div>
      <Input
        label="Search materials"
        placeholder="Search by code or name"
        value={search}
        onChange={(event) => setSearch(event.target.value)}
      />
      {materials.isLoading && (
        <div
          aria-busy="true"
          aria-label="Loading active materials"
          className="h-11 animate-pulse rounded-lg bg-gray-100 dark:bg-gray-800"
        />
      )}
      {materials.isError && (
        <Alert variant="error" title="Unable to load active materials">
          {message(materials.error, "Cannot load materials.")}{" "}
          <Button variant="ghost" size="sm" onClick={() => void materials.refetch()}>
            Retry materials
          </Button>
        </Alert>
      )}
      {!materials.isLoading && !materials.isError && materials.data?.length === 0 && (
        <p
          role="status"
          className="text-theme-sm rounded-lg border border-gray-200 p-4 text-gray-500 dark:border-gray-800 dark:text-gray-400"
        >
          No Active materials match this search.
        </p>
      )}
      <form
        className="grid grid-cols-1 gap-4 md:grid-cols-2"
        onSubmit={handleSubmit(submit)}
        noValidate
      >
        <Select
          label="Material"
          options={[
            { label: "Select an Active material", value: "" },
            ...(materials.data ?? []).map((material) => ({
              label: `${material.materialCode} — ${material.materialName}`,
              value: material.id,
            })),
          ]}
          error={formState.errors.materialId?.message}
          {...register("materialId")}
        />
        <Input
          label="Consumption per unit"
          type="number"
          min="0.000001"
          step="0.000001"
          error={formState.errors.consumptionPerUnit?.message}
          {...register("consumptionPerUnit", { valueAsNumber: true })}
        />
        <Input
          label="Unit cost (optional)"
          type="number"
          min="0.01"
          step="0.01"
          error={formState.errors.unitCost?.message}
          {...register("unitCost", {
            setValueAs: (value) => (value === "" ? undefined : Number(value)),
          })}
        />
        <Input
          label="Order index"
          type="number"
          min="0"
          step="1"
          error={formState.errors.orderIndex?.message}
          {...register("orderIndex", { valueAsNumber: true })}
        />
        <div className="md:col-span-2">
          {addLine.error && (
            <Alert variant="error" title="Unable to add BOM line">
              {message(addLine.error, "Cannot add the selected material to this BOM.")}
            </Alert>
          )}
          <Button type="submit" className="mt-3" loading={addLine.isPending}>
            Add BOM line
          </Button>
        </div>
      </form>
    </section>
  );
}
